name: kloudlite-docker-build

on:
  push:
    branches:
      - '**'



jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: name/app
    - name: Build and push
      run: echo ${{ steps.prepare.outputs.tag }}
